/* Generated by tools/build-manifest.py — do not edit by hand. */
window.QO_MANIFEST = [
  {
    "path": "sites/2go/Desktop/Screenshot 2026-07-21 134526.png",
    "site": "2go",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 134526.png"
  },
  {
    "path": "sites/2go/Desktop/Screenshot 2026-07-21 134539.png",
    "site": "2go",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 134539.png"
  },
  {
    "path": "sites/2go/Desktop/Screenshot 2026-07-21 134613.png",
    "site": "2go",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 134613.png"
  },
  {
    "path": "sites/2go/Desktop/Screenshot 2026-07-21 134637.png",
    "site": "2go",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 134637.png"
  },
  {
    "path": "sites/2go/mobile/Screenshot 2026-07-21 140426.png",
    "site": "2go",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 140426.png"
  },
  {
    "path": "sites/2go/mobile/Screenshot 2026-07-21 140441.png",
    "site": "2go",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 140441.png"
  },
  {
    "path": "sites/2go/mobile/Screenshot 2026-07-21 140502.png",
    "site": "2go",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 140502.png"
  },
  {
    "path": "sites/2go/mobile/Screenshot 2026-07-21 140524.png",
    "site": "2go",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 140524.png"
  },
  {
    "path": "sites/ASialinkage/Desktop/Hero.png",
    "site": "ASialinkage",
    "group": "Desktop",
    "name": "Hero.png"
  },
  {
    "path": "sites/ASialinkage/Desktop/Screenshot 2026-07-21 135930.png",
    "site": "ASialinkage",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 135930.png"
  },
  {
    "path": "sites/ASialinkage/Desktop/category.png",
    "site": "ASialinkage",
    "group": "Desktop",
    "name": "category.png"
  },
  {
    "path": "sites/ASialinkage/Desktop/company.png",
    "site": "ASialinkage",
    "group": "Desktop",
    "name": "company.png"
  },
  {
    "path": "sites/ASialinkage/Desktop/thumbs.png",
    "site": "ASialinkage",
    "group": "Desktop",
    "name": "thumbs.png"
  },
  {
    "path": "sites/ASialinkage/mobile/Details_mobile.png",
    "site": "ASialinkage",
    "group": "mobile",
    "name": "Details_mobile.png"
  },
  {
    "path": "sites/ASialinkage/mobile/categories_mobile.png",
    "site": "ASialinkage",
    "group": "mobile",
    "name": "categories_mobile.png"
  },
  {
    "path": "sites/ASialinkage/mobile/product_mobile.png",
    "site": "ASialinkage",
    "group": "mobile",
    "name": "product_mobile.png"
  },
  {
    "path": "sites/ASialinkage/mobile/show_product_mobile.png",
    "site": "ASialinkage",
    "group": "mobile",
    "name": "show_product_mobile.png"
  },
  {
    "path": "sites/Bancat/Desktop/Screenshot 2026-07-21 131941.png",
    "site": "Bancat",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 131941.png"
  },
  {
    "path": "sites/Bancat/Desktop/Screenshot 2026-07-21 132009.png",
    "site": "Bancat",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 132009.png"
  },
  {
    "path": "sites/Bancat/Desktop/Screenshot 2026-07-21 132043.png",
    "site": "Bancat",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 132043.png"
  },
  {
    "path": "sites/Bancat/Desktop/Screenshot 2026-07-21 132106.png",
    "site": "Bancat",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 132106.png"
  },
  {
    "path": "sites/Bancat/Desktop/Screenshot 2026-07-21 132828.png",
    "site": "Bancat",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 132828.png"
  },
  {
    "path": "sites/Bancat/Desktop/Screenshot 2026-07-21 133159.png",
    "site": "Bancat",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 133159.png"
  },
  {
    "path": "sites/Bancat/mobile/Screenshot 2026-07-21 140311.png",
    "site": "Bancat",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 140311.png"
  },
  {
    "path": "sites/Liza/Desktop/Screenshot 2026-07-21 134309.png",
    "site": "Liza",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 134309.png"
  },
  {
    "path": "sites/Liza/Desktop/Screenshot 2026-07-21 134328.png",
    "site": "Liza",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 134328.png"
  },
  {
    "path": "sites/Liza/Desktop/Screenshot 2026-07-21 134351.png",
    "site": "Liza",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 134351.png"
  },
  {
    "path": "sites/Liza/Desktop/Screenshot 2026-07-21 135407.png",
    "site": "Liza",
    "group": "Desktop",
    "name": "Screenshot 2026-07-21 135407.png"
  },
  {
    "path": "sites/Liza/mobile/Screenshot 2026-07-21 135736.png",
    "site": "Liza",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 135736.png"
  },
  {
    "path": "sites/Liza/mobile/Screenshot 2026-07-21 135820.png",
    "site": "Liza",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 135820.png"
  },
  {
    "path": "sites/Liza/mobile/Screenshot 2026-07-21 135838.png",
    "site": "Liza",
    "group": "mobile",
    "name": "Screenshot 2026-07-21 135838.png"
  }
];
