"""Regenerate js/manifest.js — the list of screenshots the panel can choose from.

Run this after adding or removing files under sites/:

    python tools/build-manifest.py

Output is a .js file rather than .json so the panel still works when
index.html is opened directly over file:// (where fetch() is blocked).
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITES = os.path.join(ROOT, "sites")
OUT = os.path.join(ROOT, "js", "manifest.js")

EXTS = {".png", ".jpg", ".jpeg", ".webp", ".avif", ".gif", ".svg"}


def main():
    entries = []
    if os.path.isdir(SITES):
        for dirpath, dirnames, filenames in os.walk(SITES):
            dirnames.sort()
            for name in sorted(filenames):
                if os.path.splitext(name)[1].lower() not in EXTS:
                    continue
                abs_path = os.path.join(dirpath, name)
                rel = os.path.relpath(abs_path, ROOT).replace(os.sep, "/")
                # site = first folder under sites/, group = the one below it
                parts = rel.split("/")
                site = parts[1] if len(parts) > 2 else "—"
                group = parts[2] if len(parts) > 3 else ""
                entries.append({
                    "path": rel,
                    "site": site,
                    "group": group,
                    "name": name,
                })

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/build-manifest.py — do not edit by hand. */\n")
        f.write("window.QO_MANIFEST = ")
        json.dump(entries, f, indent=2, ensure_ascii=False)
        f.write(";\n")

    print(f"{len(entries)} images -> {os.path.relpath(OUT, ROOT)}")
    for e in entries:
        print("  ", e["path"])


if __name__ == "__main__":
    main()
